name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    # Avoid running this workflow for forks:
    if: "github.repository == 'data-apis/dataframe-api'"
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Install Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: pip install -r ./requirements.txt

      - name: 'Build documentation'
        run: |
          # Turn warnings into errors and ensure .doctrees is not deployed:
          sphinx-build -b html -WT --keep-going spec build/draft -d doctrees

      - name: 'Configure Git'
        run: |
          git config --local user.email "noreply@data-apis.org"
          git config --local user.name "dataframe-api-bot"

      - name: 'Checkout gh-pages'
        run: |
          git fetch --all
          git checkout gh-pages

      - name: 'Copy build artifact'
        run: rm -rf ./draft && cp -R ./build/draft ./draft

      - name: 'Commit changes'
        run: git add . && git commit -m "Deploy: ${{ github.sha }}"

      - name: 'Push changes'
        if: success()
        run: git push origin gh-pages
